# Generated by Django 5.2.7 on 2025-12-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('idcourse', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=2)),
                ('instructions', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ProfitiencyLevel',
            fields=[
                ('idprofitiency', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('idteachercourse', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id_topic', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TravelPetition',
            fields=[
                ('idpetition', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=15)),
                ('start_date', models.CharField(max_length=15)),
                ('duration', models.CharField(max_length=15)),
                ('accepted', models.BooleanField(default=False)),
                ('language_knowledge', models.CharField(max_length=2)),
            ],
        ),
    ]
