# Generated by Django 5.2.7 on 2025-12-10 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appcourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HwMedia',
            fields=[
                ('idhwmedia', models.AutoField(primary_key=True, serialize=False)),
                ('media', models.FileField(upload_to='hwmedia/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubmitions',
            fields=[
                ('idsubmition', models.AutoField(primary_key=True, serialize=False)),
                ('media', models.FileField(blank=True, null=True, upload_to='sumitions/')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('idhomework', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('fkcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcourse.course')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkStudent',
            fields=[
                ('idhwstudent', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('feedback', models.CharField(blank=True, max_length=500, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('start', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('fkhw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apphomework.homework')),
            ],
        ),
    ]
